name: drb_estuary_salinity
channels:
  - anaconda
  - defaults
dependencies:
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boto3=1.18.21=pyhd3eb1b0_0
  - botocore=1.21.41=pyhd3eb1b0_1
  - bottleneck=1.3.2=py37h2a96729_1
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - ca-certificates=2021.10.26=haa95532_2
  - certifi=2021.10.8=py37haa95532_0
  - cffi=1.15.0=py37h2bbff1b_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cryptography=35.0.0=py37h71e12ea_0
  - cycler=0.10.0=py37_0
  - debugpy=1.5.1=py37hd77b12b_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - entrypoints=0.3=py37_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - icu=58.2=ha925a31_3
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py37haa95532_0
  - importlib_metadata=4.8.1=hd3eb1b0_0
  - intel-openmp=2021.4.0=haa95532_3556
  - ipykernel=6.4.1=py37haa95532_1
  - ipython=7.29.0=py37hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.0=py37haa95532_1
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - jupyter_client=7.0.6=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py37haa95532_0
  - kiwisolver=1.3.1=py37hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.2.0=hd0e1b90_0
  - libwebp=1.2.0=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - matplotlib=3.4.3=py37haa95532_0
  - matplotlib-base=3.4.3=py37h49ac443_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - munkres=1.1.4=py_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - numexpr=2.7.3=py37hb80d3ca_1
  - numpy=1.21.2=py37hfca59bb_0
  - numpy-base=1.21.2=py37h0829f74_0
  - olefile=0.46=py37_0
  - openssl=1.1.1l=h2bbff1b_0
  - pandas=1.3.4=py37h6214cd6_0
  - parso=0.8.2=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py37hd45dc43_0
  - pip=21.2.4=py37haa95532_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h6538335_2
  - pysocks=1.7.1=py37_1
  - python=3.7.6=h60c2a47_2
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pytz=2021.3=pyhd3eb1b0_0
  - pywin32=228=py37hbaba5e8_1
  - pyzmq=22.2.1=py37hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - regex=2021.8.3=py37h2bbff1b_0
  - s3transfer=0.5.0=pyhd3eb1b0_0
  - setuptools=58.0.4=py37haa95532_0
  - sip=4.19.8=py37h6538335_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - tk=8.6.11=h2bbff1b_0
  - tornado=6.1=py37h2bbff1b_0
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0