fetch_usgs.py:
  # choose where you want to write your data outputs: local or S3
  write_location: 'S3'
  # set name of AWS profile storing credentials for S3
  aws_profile: 'dev'
  # set AWS bucket to read/write to
  s3_bucket: 'drb-estuary-salinity'

  # usgs nwis sites we want to fetch data for
  site_ids:
    #- '01411390' # Cape May Harbor at Cape May NJ
    - '01463500' # Delaware River at Trenton NJ
    #- '01464040' # Delaware River at Marine Terminal at Trenton NJ
    #- '014670261' # Delaware River at Pennypack Woods PA
    #- '01467059' # Delaware River at Riverton NJ
    #- '01467200' # Delaware River at Penn's Landing, Philadelphia, PA
    - '01474500' # Schuylkill River at Philadelphia, PA
    #- '01474703' # Delaware River at Fort Mifflin at Philadelphia, PA
    #- '01477050' # DELAWARE RIVER AT CHESTER PA
    #- '01482695' # C AND D CANAL NR DELAWARE CITY, DE
    #- '01482800' # Delaware River at Reedy Island Jetty, DE
 
  # start and end dates for data fetch
  # should be in the format 'YYYY-MM-DD'
  start_dt: '2000-01-01'
  end_dt: '2019-12-31'

fetch_noaa_nos.py:
  #choose where you want to write your data outputs: local or S3
  write_location: 'local'
  #set name of AWS profile storing credentials for S3
  aws_profile: 'dev'
  #set AWS bucket to read/write to
  s3_bucket: 'drb-estuary-salinity'
  #set up AWS client
  s3_client: utils.prep_write_location(write_location, aws_profile)

  station_id: '8573927'

  datum: 'MLLW'
  # options:
  # HAT: Highest Astronomical Tide
  # MHHW: Mean Higher High Water
  # MHW: Mean High Water
  # DTL: Diurnal Tide Level
  # MTL: Mean Tide Level
  # MSL: Mean Sea Level
  # MLW: Mean Low Water
  # MLLW: Mean Lower Low Water
  # LAT: Lowest Astronomical Tide
  # GT: Great Diurnal Range
  # MN: Mean Diurnal Range
  # DHQ: Mean Diurnal High Water Inequality
  # HWI: Greenwich High Water Interval
  # LWI: Greenwich Low Water Interval
  # Max Tide: Highest Observed Tide
  # Min Tide: Lowest Observed Tide
  # Station Datum: fixed base elevation at a tide station
  # National Tidal Datum Epoch: The specific 19-year period adopted by the National Ocean Service as the official time
  # segment over which tide observations are taken and reduced to obtain mean values (e.g., mean lower low water, etc.) for tidal datums.

  product: 'water_level'
  # options: water_level, air_temperature, water_temperature, wind, air_pressure, air_gap, conductivity, visibility,
  # humidity, salinity, hourly_height, high_low, daily_mean, monthly_mean, one_minute_water_level, predictions, datums,
  # currents, and currents_predictions.

  time_zone: 'GMT'
  # options:
  # gmt: Greenwich Mean Time
  # lst: Local Standard Time. The time local to the requested station.
  # lst_ldt: Local Standard/Local Daylight Time. The time local to the requested station.

  units: 'metric'
  # options: english and metric

  file_format: 'csv'

  start_dt: '20190101'
  end_dt: '20191231'