#choose where you want to write your data outputs: local or S3
write_location: 'local'
#set name of AWS profile storing credentials for S3
aws_profile: 'dev'
#set AWS bucket to read/write to
s3_bucket: 'drb-estuary-salinity'

# options:
# HAT: Highest Astronomical Tide
# MHHW: Mean Higher High Water
# MHW: Mean High Water
# DTL: Diurnal Tide Level
# MTL: Mean Tide Level
# MSL: Mean Sea Level
# MLW: Mean Low Water
# MLLW: Mean Lower Low Water
# LAT: Lowest Astronomical Tide
# GT: Great Diurnal Range
# MN: Mean Diurnal Range
# DHQ: Mean Diurnal High Water Inequality
# HWI: Greenwich High Water Interval
# LWI: Greenwich Low Water Interval
# Max Tide: Highest Observed Tide
# Min Tide: Lowest Observed Tide
# Station Datum: fixed base elevation at a tide station
# National Tidal Datum Epoch: The specific 19-year period adopted by the National Ocean Service as the official time
# segment over which tide observations are taken and reduced to obtain mean values (e.g., mean lower low water, etc.) for tidal datums.
datum: 'MSL'

# options:
# gmt: Greenwich Mean Time
# lst: Local Standard Time. The time local to the requested station.
# lst_ldt: Local Standard/Local Daylight Time. The time local to the requested station.
time_zone: 'GMT'

# options: english and metric
units: 'metric'

# options: csv, json, xml
file_format: 'json'

start_year: '2000'
end_year: '2019'
